// <auto-generated />
namespace VideoRentalSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MovieDateAddedDateTime2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieDateAddedDateTime2));
        
        string IMigrationMetadata.Id
        {
            get { return "201907291345308_MovieDateAddedDateTime2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
